openapi: 3.0.3
info:
  title: teacher Information Management System
  version: 1.0.0
servers:
  - url: https://localhost:8081/api
paths:
  /teachers:
    get:
      operationId: getTeachers
      summary: Get all teachers
      responses:
        200:
          description: Get all teachers successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Teacher'
              example: [{ "id": 1, "code": "001", "name": "Khanh" }, { "id": 2, "code": "002", "name": "Quan" }]
  /teachers/{id}:
    get:
      operationId: getTeacherById
      summary: Get a teacher by id
      parameters:
        - name: id
          in: path
          description: "Id of the Teacher"
          required: true
          schema:
            type: string
      responses:
        200:
          description: Get teacher information successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Teacher'
              example: { "id": 1, "code": "001", "name": "Khanh" }
    delete:
      operationId: deleteTeacherById
      summary: Delete a teacher by id
      parameters:
        - name: id
          in: path
          description: "Id of the Teacher"
          required: true
          schema:
            type: string
      responses:
        200:
          description: Delete teacher information successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example: { "message": "Teacher deleted!"}
components:
  schemas:
    Teacher:
      type: object
      properties:
        id:
          type: integer
          format: int64
        code:
          type: string
        name:
          type: string
    Response:
      type: object
      properties:
        message:
          type: string